version: '3'
services:
  # Node.js app
  todo-app:
    container_name: todo-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PSQL_HOST: host.docker.internal
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/todoapi
    networks:
      - node-network 
    depends_on:
      - todo-db

  # PostgreSQL database
  todo-db:
    container_name: todo-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_todo
    ports:
      - "5432:5432"  # Forwarding host port 5432 to container port 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data  
    networks:
      - node-network 

networks:
  node-network:
    driver: bridge  # Using the bridge network driver to connect the app and db services

volumes:
  postgres-data:
